### ISSUE TITLE
class绑定切换的时候安卓端后台或报异常

### ISSUE THREAD

**Issue by AnkerCheng** [bmfe/eros-docs#33]
`02-15 10:39:53.367 548-548/com.android.inputmethod.latin V/InputMethodService: onEvaluateInputViewShown: config.hardKeyboardHidden = 1
02-15 10:39:53.367 548-548/com.android.inputmethod.latin V/InputMethodService: onEvaluateInputViewShown: config.hardKeyboardHidden = 1
02-15 10:39:54.191 3332-3348/com.benmu.wx V/Color_Parser: java.lang.NullPointerException
        at com.taobao.weex.utils.WXResourceUtils$ColorConvertHandler$3.handle(WXResourceUtils.java:401)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:246)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:232)
        at com.taobao.weex.dom.WXTextDomObject.updateStyleImp(WXTextDomObject.java:305)
        at com.taobao.weex.dom.WXTextDomObject.updateStyleAndText(WXTextDomObject.java:281)
        at com.taobao.weex.dom.WXTextDomObject.layoutBefore(WXTextDomObject.java:184)
        at com.taobao.weex.dom.DOMActionContextImpl$1.accept(DOMActionContextImpl.java:206)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:125)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:132)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:132)
        at com.taobao.weex.dom.DOMActionContextImpl.layout(DOMActionContextImpl.java:200)
        at com.taobao.weex.dom.DOMActionContextImpl.batch(DOMActionContextImpl.java:179)
        at com.taobao.weex.dom.WXDomManager.batch(WXDomManager.java:141)
        at com.taobao.weex.dom.WXDomHandler.handleMessage(WXDomHandler.java:86)
        at com.taobao.weex.common.WXThread$SafeCallback.handleMessage(WXThread.java:73)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
02-15 10:39:54.191 3332-3348/com.benmu.wx D/CLog: java.lang.NullPointerException
        at com.taobao.weex.utils.WXResourceUtils$ColorConvertHandler$3.handle(WXResourceUtils.java:401)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:246)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:232)
        at com.taobao.weex.dom.WXTextDomObject.updateStyleImp(WXTextDomObject.java:305)
        at com.taobao.weex.dom.WXTextDomObject.updateStyleAndText(WXTextDomObject.java:281)
        at com.taobao.weex.dom.WXTextDomObject.layoutBefore(WXTextDomObject.java:184)
        at com.taobao.weex.dom.DOMActionContextImpl$1.accept(DOMActionContextImpl.java:206)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:125)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:132)
        at com.taobao.weex.dom.WXDomObject.traverseTree(WXDomObject.java:132)
        at com.taobao.weex.dom.DOMActionContextImpl.layout(DOMActionContextImpl.java:200)
        at com.taobao.weex.dom.DOMActionContextImpl.batch(DOMActionContextImpl.java:179)
        at com.taobao.weex.dom.WXDomManager.batch(WXDomManager.java:141)
        at com.taobao.weex.dom.WXDomHandler.handleMessage(WXDomHandler.java:86)
        at com.taobao.weex.common.WXThread$SafeCallback.handleMessage(WXThread.java:73)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:137)
        at android.os.HandlerThread.run(HandlerThread.java:60)
02-15 10:39:54.203 3332-3348/com.benmu.wx D/LineHeight: 登录 ; start 0; end 2; spanstartv 0; v 0; fm FontMetricsInt: top=-41 ascent=-35 descent=9 bottom=11 leading=0
02-15 10:39:54.207 3332-3348/com.benmu.wx D/CLog: LineHeight:登录 ; start 0; end 2; spanstartv 0; v 0; fm FontMetricsInt: top=-41 ascent=-35 descent=9 bottom=11 leading=0
02-15 10:39:54.219 3332-3348/com.benmu.wx D/LineHeight: 登录 ; start 0; end 2; spanstartv 0; v 0; fm FontMetricsInt: top=-41 ascent=-35 descent=9 bottom=11 leading=0
02-15 10:39:54.219 3332-3348/com.benmu.wx D/CLog: LineHeight:登录 ; start 0; end 2; spanstartv 0; v 0; fm FontMetricsInt: top=-41 ascent=-35 descent=9 bottom=11 leading=0
02-15 10:39:54.223 3332-3348/com.benmu.wx D/updateDomObj: time:0
02-15 10:39:54.227 3332-3348/com.benmu.wx D/CLog: updateDomObj:time:0
02-15 10:39:54.231 3332-3348/com.benmu.wx D/weex: mInstanceId  15 batch used 44
02-15 10:39:54.231 3332-3348/com.benmu.wx D/CLog: weex:mInstanceId  15 batch used 44
02-15 10:39:54.247 3332-3332/com.benmu.wx V/Color_Parser: java.lang.NullPointerException
        at com.taobao.weex.utils.WXResourceUtils$ColorConvertHandler$3.handle(WXResourceUtils.java:401)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:246)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:232)
        at com.taobao.weex.ui.component.WXComponent.setBackgroundColor(WXComponent.java:1408)
        at com.taobao.weex.ui.component.WXComponent.setProperty(WXComponent.java:805)
        at com.taobao.weex.ui.component.WXText.setProperty(WXText.java:152)
        at com.taobao.weex.ui.component.WXComponent.updateProperties(WXComponent.java:747)
        at com.taobao.weex.dom.action.UpdateStyleAction.executeRender(UpdateStyleAction.java:105)
        at com.taobao.weex.dom.RenderActionTask.execute(RenderActionTask.java:50)
        at com.taobao.weex.ui.WXRenderManager$1.run(WXRenderManager.java:104)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
02-15 10:39:54.247 3332-3332/com.benmu.wx D/CLog: java.lang.NullPointerException
        at com.taobao.weex.utils.WXResourceUtils$ColorConvertHandler$3.handle(WXResourceUtils.java:401)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:246)
        at com.taobao.weex.utils.WXResourceUtils.getColor(WXResourceUtils.java:232)
        at com.taobao.weex.ui.component.WXComponent.setBackgroundColor(WXComponent.java:1408)
        at com.taobao.weex.ui.component.WXComponent.setProperty(WXComponent.java:805)
        at com.taobao.weex.ui.component.WXText.setProperty(WXText.java:152)
        at com.taobao.weex.ui.component.WXComponent.updateProperties(WXComponent.java:747)
        at com.taobao.weex.dom.action.UpdateStyleAction.executeRender(UpdateStyleAction.java:105)
        at com.taobao.weex.dom.RenderActionTask.execute(RenderActionTask.java:50)
        at com.taobao.weex.ui.WXRenderManager$1.run(WXRenderManager.java:104)
        at com.taobao.weex.common.WXThread$SafeRunnable.run(WXThread.java:48)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
`

**Comment by PerseveranceZ** [comment]
这些报错信息无用

issue 请移步 [https://github.com/bmfe/eros](https://github.com/bmfe/eros)
